### ISSUE TITLE
diary 에러사항

### ISSUE THREAD

**Issue by ozingmw** [ozingmw/capstone#40]

**Comment by ozingmw** [comment]
@Ccolornyong

**Comment by ozingmw** [comment]
<img width="200" alt="image" src="https://github.com/user-attachments/assets/a13de442-aab7-49a7-8674-e3c876975b16">

작성화면에서 현재 요일에 다른 날짜가 입력되어있음

**Comment by ozingmw** [comment]
<img width="91" alt="image" src="https://github.com/user-attachments/assets/6f0289a8-621b-4936-87fe-ca858e49f863">

문답작성, 일기작성을 누를경우 뒤로가기 계속 나옴

**Comment by ozingmw** [comment]
~~파일명 진짜 꿀밤마렵네~~

**Comment by ozingmw** [comment]
<img width="395" alt="image" src="https://github.com/user-attachments/assets/157e13e4-0df3-45bb-9b7d-4b0f28bd1d50">

여기서 멈춤

**Comment by ozingmw** [comment]
<img width="251" alt="image" src="https://github.com/user-attachments/assets/934eabdb-f4c5-4fe4-bd42-6e041a7e3ff4">

여기서 넘어가는 버튼이 없음

**Comment by ozingmw** [comment]
> <img alt="image" width="251" src="https://private-user-images.githubusercontent.com/69336570/370131354-934eabdb-f4c5-4fe4-bd42-6e041a7e3ff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNTI5NDcsIm5iZiI6MTcyNzE1MjY0NywicGF0aCI6Ii82OTMzNjU3MC8zNzAxMzEzNTQtOTM0ZWFiZGItZjRjNS00ZmU0LWJkNDItNmUwNDFhN2UzZmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA0MzcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyM2I5ZTI3NzVkMWU3YjIyZDMxNzEwYmJkZmQ3NGI5MDQwYmVjNmQ1MDBmNWY0ZmRkMmFlOTA5MzM5OWY4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hNPtZigGh84E_X62QjE0BgErQHQOznbijyx7V0XM9UQ">
> 여기서 넘어가는 버튼이 없음

엥 우측 위에 있네?
근데 다음으로 안넘어감

**Comment by ozingmw** [comment]
<img width="379" alt="image" src="https://github.com/user-attachments/assets/6de931d3-eb99-4f7a-a720-9728e55615d6">

이 화면도 저장 눌러도 무응답

**Comment by ozingmw** [comment]
<img width="353" alt="image" src="https://github.com/user-attachments/assets/9e0367bf-9a2a-4f9a-9c58-08369235bbb5">

괜찮아요 클릭시 다른 화면으로 넘어가야할듯?

**Comment by Ccolornyong** [comment]
> <img alt="image" width="353" src="https://private-user-images.githubusercontent.com/69336570/370132124-9e0367bf-9a2a-4f9a-9c58-08369235bbb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NzYwNDIsIm5iZiI6MTcyNzY3NTc0MiwicGF0aCI6Ii82OTMzNjU3MC8zNzAxMzIxMjQtOWUwMzY3YmYtOWEyYS00ZjlhLTljNTgtMDgzNjkyMzViYmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA1NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOGNjYzM5MjhlNWNlNjY1N2MxNTNmNDYyN2I4NDYwMDk3ODFjMTkyNzAwMWYwM2Y5MmUwNThlOGRjYjgxNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9aZJTpFR4QHIJpoCC5Aukb4XThhw9OicdSG2gEfkLwI">
> 괜찮아요 클릭시 다른 화면으로 넘어가야할듯?

괜찮아요 클릭 시 diary8.dart 로 넘어가욥
문구는 안받고 작성했던 일기 화면으로 넘어가는 형식이고 해당 화면에는 감정 마크 표시 있음

**Comment by Ccolornyong** [comment]
> <img alt="image" width="251" src="https://private-user-images.githubusercontent.com/69336570/370131354-934eabdb-f4c5-4fe4-bd42-6e041a7e3ff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NzYwNDIsIm5iZiI6MTcyNzY3NTc0MiwicGF0aCI6Ii82OTMzNjU3MC8zNzAxMzEzNTQtOTM0ZWFiZGItZjRjNS00ZmU0LWJkNDItNmUwNDFhN2UzZmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA1NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYjVhZDc4ZWFiOWE1NTk0NjFjYTk5N2ExNjI2MDEyZDY2YWFhNmIyZGUzM2ZlYjEwYTk0ZmFlYTA5MTBjOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dGDMYsuZ-TxKABL3VH2MKMaG_xHyVgoVp4AcJJoMl6k">
> 여기서 넘어가는 버튼이 없음 엥 우측 위에 있네? 근데 다음으로 안넘어감 -> 넘어가질거같은데 아이폰 기준 너무 위에있어서 클릭이 안됨

상단 SizedBox 50에서 100으로 바꿨는데 어떤지 확인해주세요

**Comment by Ccolornyong** [comment]
> <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/69336570/370131268-157e13e4-0df3-45bb-9b7d-4b0f28bd1d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NzYwNDIsIm5iZiI6MTcyNzY3NTc0MiwicGF0aCI6Ii82OTMzNjU3MC8zNzAxMzEyNjgtMTU3ZTEzZTQtMGRmMy00NWJiLTliN2QtNGIwZjI4YmQxZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA1NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwM2JlNzM1YzM4MGM4NDVhZTJmYWU3ZTYxY2Y2NGUyYzEwOGE3YzE3ODRjNTVhYjBmYmVhYjlkYWFiODUzZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vHviSpxISSut1GF-RQzlqeWCc-A8tSuR1xxb5deY2cc">

> 여기서 멈춤 -> 임시로 2초뒤에 넘어가기로 변경

이건 어제 대면 작업할 때 이야기 된 부분으로 개 <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/69336570/370131268-157e13e4-0df3-45bb-9b7d-4b0f28bd1d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NzYwNDIsIm5iZiI6MTcyNzY3NTc0MiwicGF0aCI6Ii82OTMzNjU3MC8zNzAxMzEyNjgtMTU3ZTEzZTQtMGRmMy00NWJiLTliN2QtNGIwZjI4YmQxZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA1NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwM2JlNzM1YzM4MGM4NDVhZTJmYWU3ZTYxY2Y2NGUyYzEwOGE3YzE3ODRjNTVhYjBmYmVhYjlkYWFiODUzZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vHviSpxISSut1GF-RQzlqeWCc-A8tSuR1xxb5deY2cc">

> 여기서 멈춤 -> 임시로 2초뒤에 넘어가기로 변경

이건 어제 대면 작업할 때 이야기 된 부분으로 개발 작업시에는 해당 화면 제외하고 진행하기로 함

**Comment by Ccolornyong** [comment]
> <img alt="image" width="88" src="https://private-user-images.githubusercontent.com/69336570/370118771-742ba054-d067-4b3f-ac3e-8ebdd5b798fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NzY0OTQsIm5iZiI6MTcyNzY3NjE5NCwicGF0aCI6Ii82OTMzNjU3MC8zNzAxMTg3NzEtNzQyYmEwNTQtZDA2Ny00YjNmLWFjM2UtOGViZGQ1Yjc5OGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA2MDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYmE4YjIxYzYyNmZjYmI1YzBjZWRmOWU0M2YyOGQ3MTJlNjdiZDk3YmMxYzdkZTM1NzcxMzAwOTVlZGQ3YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gimp7v84oIRe0-NYiWPOVGw6JUDM93ozwl300oYFcKk">
> 저장 이후 수정으로 변경되었는데 수정 눌러도 똑같이 저장되었습니다.로 나옴
> 
> <img alt="image" width="348" src="https://private-user-images.githubusercontent.com/69336570/370118863-a8aeda1e-b903-43bb-a6c9-4074964bedf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NzY0OTQsIm5iZiI6MTcyNzY3NjE5NCwicGF0aCI6Ii82OTMzNjU3MC8zNzAxMTg4NjMtYThhZWRhMWUtYjkwMy00M2JiLWE2YzktNDA3NDk2NGJlZGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA2MDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTY3MWZjZTZmNjgyOTQ5YTkyYTRlNmZiZmZjZWZhNjhkNTAzMDZhN2RiYjIzODI3ZDY1MzgzM2Q2YjczYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gBJyzKmZK9TWAIH6Yhbiqt3Hc0oGdLg7C8mCjd4Stcw">

> 그리고 이때도 뒤로가기 보임 -> 뒤로가기 누르면 수정할수 있게 바뀜

뒤로 가기 버튼 전부 수정하여 삭제 함

**Comment by ozingmw** [comment]
@Ccolornyong 
예
변경하면 commit 메시지에 해당 이슈 언급하면 됩니당
